# Generated by Django 5.1.7 on 2025-03-24 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_remove_page_background_image_remove_page_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='content',
            field=models.TextField(default='Placeholder content'),
            preserve_default=False,
        ),
    ]
