# Generated by Django 5.1.7 on 2025-03-25 09:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_page_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='PricingPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('segment', models.CharField(choices=[('all_inclusive', 'All Inclusive Wedding Package'), ('venue_inclusive', 'Venue Inclusive Package'), ('weekday', 'Weekday Package')], max_length=20)),
                ('package_number', models.PositiveSmallIntegerField()),
                ('package_name', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='packages/')),
                ('current_version', models.PositiveIntegerField(default=1)),
                ('approved', models.BooleanField(default=False)),
                ('approved_by', models.CharField(blank=True, max_length=100, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PricingPackageVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField()),
                ('package_name', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='packages/versions/')),
                ('uploader', models.CharField(max_length=100)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('approved', models.BooleanField(default=False)),
                ('approved_by', models.CharField(blank=True, max_length=100, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('pricing_package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='cms.pricingpackage')),
            ],
        ),
    ]
