# Generated by Django 5.1.7 on 2025-03-25 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_pricingpackage_pricingpackageversion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='pricingpackage',
            name='package_number',
        ),
        migrations.AddField(
            model_name='pricingpackage',
            name='year',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cms.year'),
        ),
    ]
